# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram
  pod 'FBSDKLoginKit'
  pod 'Alamofire', '~> 5.4'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~>7.0'
  pod 'PanModal'
  pod 'ScrollingPageControl'
  pod 'Tabman', '~> 2.11'
  pod 'YPImagePicker'
  use_frameworks!

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
end
